name: Sortal
version: 5.0
author: Lolmewn
website: http://mcstats.org/plugin/Sortal/
main: nl.lolmewn.sortal.Main
softdepend: [Vault]
description: Sign based teleportation! 
commands:
  sortal:
    description: Just the Sortal command
    usage: /<command>
permissions:
  sortal.*:
    description: Gives access to all sortal commands and usages
    children:
      sortal.createwarp: true
      sortal.delwarp: true
      sortal.list: true
      sortal.unregister: true
      sortal.directwarp: true
      sortal.setuses: true
      sortal.placesign: true
      sortal.warp: true
  sortal.createwarp:
    default: op
  sortal.delwarp:
    default: op
  sortal.list:
    default: op
  sortal.unregister:
    default: op
  sortal.directwarp:
    default: op
  sortal.setuses:
    default: op
  sortal.placesign:
    default: op
  sortal.warp:
    default: true